"use client";
import { useEffect,useRef,useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { X, Minus, Plus, Trash2, ArrowRight } from "lucide-react";
import { readCart,writeCart,removeLogo } from "@/lib/shop/cart";
import { cartIssues, productQuantity } from "@/lib/shop/cart-state";
import { cardOffer } from "@/lib/shop/offers";
import { taxFor } from "@/lib/shop/totals";
import { type Product,priceLabel } from "@/lib/shop/catalogue";
import type { CartItem } from "@/lib/shop/validation";
export function CartDrawer({products,onClose}:{products:Product[];onClose:()=>void}){
 const ref=useRef<HTMLDialogElement>(null);const [items,setItems]=useState<CartItem[]>([]);const [error,setError]=useState("");
 useEffect(()=>{const dialog=ref.current;dialog?.showModal();const before=document.body.style.overflow;document.body.style.overflow="hidden";const sync=()=>setItems(readCart());sync();window.addEventListener("cart-updated",sync);window.addEventListener("storage",sync);return()=>{dialog?.close();document.body.style.overflow=before;window.removeEventListener("cart-updated",sync);window.removeEventListener("storage",sync);};},[]);
 function update(next:CartItem[]){try{writeCart(next);setError("");return true;}catch{setError("Your browser could not save this change. Please retry.");return false;}}
 const gross=items.reduce<number|null>((sum,i)=>{const p=products.find(p=>p.slug===i.productSlug);const v=p?.variants.find(v=>v.id===i.variantId);return sum===null||v?.price_paise==null?null:sum+v.price_paise*i.quantity;},0);
 const issues=cartIssues(items,products);
 const discount=cardOffer(items,products).discount;const subtotal=gross===null?null:gross-discount;
 return <dialog ref={ref} className="cart-drawer" aria-labelledby="cart-drawer-title" onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="cart-drawer-inner"><header><div><p className="shop-eyebrow">YOUR NEXT CONNECTION</p><h2 id="cart-drawer-title">Your cart</h2></div><button autoFocus onClick={onClose} aria-label="Close cart"><X/></button></header><div className="cart-drawer-items">{items.length===0?<div className="drawer-empty"><h3>Make room for a connection.</h3><p>Your cart is empty.</p><Link href="/#collection" className="shop-button" onClick={onClose}>Explore products</Link></div>:items.map(i=>{const p=products.find(p=>p.slug===i.productSlug);const v=p?.variants.find(v=>v.id===i.variantId);const max=Math.min(50,(p?.stock??50)-productQuantity(items,i.productSlug)+i.quantity);return <article key={i.id}>{v&&<Image src={v.image} width={90} height={90} alt=""/>}<div><Link href={"/products/"+i.productSlug} onClick={onClose}>{p?.name||"Unavailable product"}</Link><small>{v?.name}{i.logoName?" · Logo attached":""}</small><strong>{priceLabel(v?.price_paise==null?null:v.price_paise*i.quantity)}</strong><div className="drawer-quantity"><button disabled={i.quantity<=1} aria-label={"Decrease quantity of "+p?.name} onClick={()=>update(items.map(r=>r.id===i.id?{...r,quantity:r.quantity-1}:r))}><Minus size={15}/></button><span aria-label="Quantity">{i.quantity}</span><button disabled={i.quantity>=max} aria-label={"Increase quantity of "+p?.name} onClick={()=>update(items.map(r=>r.id===i.id?{...r,quantity:r.quantity+1}:r))}><Plus size={15}/></button><button aria-label={"Remove "+p?.name} onClick={()=>{if(update(items.filter(r=>r.id!==i.id))&&i.logoId)void removeLogo(i.logoId).catch(()=>{});}}><Trash2 size={16}/></button></div>{i.quantity>max&&<p className="shop-error">Only {max} currently available. Update your quantity.</p>}</div></article>;})}</div>{error&&<p role="alert" className="shop-error">{error}</p>}{items.length>0&&<footer><div><span>Products</span><strong>{priceLabel(gross)}</strong></div>{discount>0&&<div><span>Free card offer</span><strong>−{priceLabel(discount)}</strong></div>}<div><span>Subtotal</span><strong>{priceLabel(subtotal)}</strong></div><div><span>Tax (18%)</span><strong>{priceLabel(subtotal===null?null:taxFor(subtotal))}</strong></div><p>Shipping calculated for your PIN at checkout. Design confirmed with you on WhatsApp.</p>{issues.length>0&&<div role="alert" className="shop-error">{issues.map(issue=><p key={issue}>{issue}</p>)}</div>}{issues.length===0?<Link href="/checkout" className="shop-button" onClick={()=>{sessionStorage.removeItem("nfc-checkout-mode");onClose();}}>Checkout <ArrowRight size={18}/></Link>:<button className="shop-button" disabled>Update cart to checkout</button>}<button className="plain-button" onClick={onClose}>Continue shopping</button></footer>}</div></dialog>;
}
