"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { LockKeyhole,ArrowRight } from "lucide-react";
import { readCart,readLogo } from "@/lib/shop/cart";
import { addressSchema,cartItemSchema,type CartItem } from "@/lib/shop/validation";
import { type Product,priceLabel } from "@/lib/shop/catalogue";
import { createClient } from "@/lib/supabase/client";
import { GoogleButton } from "./google-button";
async function jsonRequest(path:string,body:unknown,method="POST"){const res=await fetch(path,{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw new Error(data.error||"Please try again.");return data;}
export function Checkout({products,email,enabled,initialItems,popup=false}:{products:Product[];email:string|null;enabled:boolean;initialItems?:CartItem[];popup?:boolean}){
 const [items,setItems]=useState<CartItem[]>(initialItems||[]),[ready,setReady]=useState(!!initialItems),[error,setError]=useState(""),[busy,setBusy]=useState(false),[shipping,setShipping]=useState<number|null>(null),[quotedPin,setQuotedPin]=useState("");
 useEffect(()=>{if(initialItems)return;const timer=setTimeout(()=>{try{const buy=new URLSearchParams(location.search).get("buy")==="now";if(buy)sessionStorage.setItem("nfc-checkout-mode","buy");const raw=sessionStorage.getItem("nfc-checkout-mode")==="buy"?JSON.parse(sessionStorage.getItem("nfc-buy-now")||"[]"):readCart();setItems(cartItemSchema.array().parse(raw));}catch{setItems([]);}setReady(true);},0);return()=>clearTimeout(timer);},[initialItems]);
 const total=items.reduce((sum,i)=>{const v=products.find(p=>p.slug===i.productSlug)?.variants.find(v=>v.id===i.variantId);return sum===null||v?.price_paise==null?null:sum+v.price_paise*i.quantity;},0 as number|null);
 async function quote(form:HTMLFormElement){const input=Object.fromEntries(new FormData(form));const parsed=addressSchema.safeParse({...input,country:"India"});if(!parsed.success){setError(parsed.error.issues[0].message);return;}setBusy(true);setError("");try{const q=await jsonRequest("/api/shop/quote",{items,pincode:parsed.data.pincode});setShipping(q.amount);setQuotedPin(parsed.data.pincode);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function pay(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!enabled)return;setError("");const form=e.currentTarget;const f=Object.fromEntries(new FormData(form));const parsed=addressSchema.safeParse({...f,country:"India"});if(!parsed.success){setError(parsed.error.issues[0].message);return;}if(shipping===null||quotedPin!==parsed.data.pincode){await quote(form);return;}if(f.consent!=="on"){setError("Please agree to design contact and the order policies.");return;}setBusy(true);try{const mapped=[];for(const item of items){if(item.logoId){const blob=await readLogo(item.logoId);if(!blob)throw new Error("A logo is missing from this browser. Re-add the product with your logo.");const up=await jsonRequest("/api/shop/assets",{name:item.logoName||"logo.png",size:blob.size});const {error:upError}=await createClient().storage.from("order-logos").uploadToSignedUrl(up.path,up.token,blob,{contentType:"image/png"});if(upError)throw new Error("Logo upload failed. Please retry.");await jsonRequest("/api/shop/assets",{id:up.id},"PUT");mapped.push({...item,logoId:up.id});}else mapped.push(item);}
 const signature=JSON.stringify({items,address:parsed.data,shipping});let saved:{signature:string;requestId:string}|null=null;try{saved=JSON.parse(sessionStorage.getItem("nfc-payment-request")||"null");}catch{}const requestId=saved?.signature===signature?saved.requestId:crypto.randomUUID();sessionStorage.setItem("nfc-payment-request",JSON.stringify({signature,requestId}));
 const payment=await jsonRequest("/api/shop/checkout",{items:mapped,address:parsed.data,requestId,shippingPaise:shipping,consent:true});const paymentForm=document.createElement("form");paymentForm.method="POST";paymentForm.action=payment.action;for(const [name,value]of Object.entries(payment.fields)){const input=document.createElement("input");input.type="hidden";input.name=name;input.value=String(value);paymentForm.append(input);}document.body.append(paymentForm);paymentForm.submit();
 }catch(e){setError((e as Error).message);setBusy(false);}}
 if(!ready)return <p role="status">Preparing your checkout…</p>;
 if(!items.length)return <div className="shop-empty"><h2>Your bag is empty.</h2><Link className="shop-button" href="/">Find your card <ArrowRight size={16}/></Link></div>;
 return <><div className="checkout-step"><span>01 / Your products</span><span>02 / Your design</span><strong>03 / Checkout</strong></div>{!enabled&&<p className="preview-note">Launch preview — explore checkout below. Prices and shipping will be confirmed before orders open. No payment or order is taken here.</p>}
 <div className="checkout-layout"><div>{!email?<div className="auth-card" style={{margin:"0 0 25px",maxWidth:"none"}}><h2>Keep your order close.</h2><p>Sign in with Google to checkout and track your order. Your bag and logo stay saved in this browser.</p><GoogleButton next="/checkout" popup={popup}/></div>:<p>Signed in as {email}</p>}
 <form id="checkout-details" onSubmit={pay} className="checkout-form"><h2 className="full">Where should we send it?</h2>
 {[["name","Full name","name"],["phone","WhatsApp number","tel"],["line1","Address","address-line1"],["line2","Apartment / landmark (optional)","address-line2"],["city","City","address-level2"],["state","State","address-level1"],["pincode","PIN code","postal-code"]].map(([name,label,auto])=><label key={name} className={name.startsWith("line")?"full":""}>{label}<input name={name} required={name!=="line2"} autoComplete={auto} type={name==="phone"?"tel":"text"} maxLength={name==="phone"?10:name==="pincode"?6:200} inputMode={["phone","pincode"].includes(name)?"numeric":undefined} onChange={()=>{if(name==="pincode"){setShipping(null);setQuotedPin("");}}}/></label>)}
 <label>Country<input value="India" readOnly/></label><p className="full customisation-note">Our team will contact you on WhatsApp to collect your destination links and confirm your design.</p>
 <label className="consent full"><input type="checkbox" name="consent" required/> <span>I agree to be contacted about my design and order. I have read the <Link href="/privacy">privacy information</Link>{enabled&&<> and <Link href="/policies">order policies</Link></>}.</span></label>
 {error&&<p className="shop-error full" role="alert">{error}</p>}
 <button className="shop-button full" disabled={!enabled||!email||busy||total===null}>{busy?"Please wait…":!enabled?"Checkout opens soon":shipping===null?"Calculate shipping":"Continue to PayU"} <LockKeyhole size={16}/></button></form></div>
 <aside className="order-summary"><h2>Your order</h2>{items.map(i=>{const p=products.find(p=>p.slug===i.productSlug);const v=p?.variants.find(v=>v.id===i.variantId);return <div key={i.id}><span>{p?.name}<br/><small>{v?.name} · Qty {i.quantity}{i.logoName?" · Logo attached":""}</small></span><strong>{priceLabel(v?.price_paise==null?null:v.price_paise*i.quantity)}</strong></div>;})}<div><span>Shipping</span><strong>{shipping===null?"Calculated next":priceLabel(shipping)}</strong></div><div><span>Total</span><strong>{priceLabel(total!==null&&shipping!==null?total+shipping:null)}</strong></div><p>Made to order. Design approved by you before production.</p><Link href="/cart" className="plain-button" onClick={()=>{sessionStorage.removeItem("nfc-checkout-mode");sessionStorage.removeItem("nfc-payment-request");}}>Edit your bag</Link></aside></div></>;
}
