"use client";
import { StickyMobileCart } from "./sticky-mobile-cart";
import { CartExtras } from "./cart-extras";
import { useRef,useState } from "react";
import type { CartItem } from "@/lib/shop/validation";
import { CheckoutDialog } from "./checkout-dialog";
import { ArrowRight, Check, Upload, ShoppingBag, ShieldCheck } from "lucide-react";
import { type Product,priceLabel } from "@/lib/shop/catalogue";
import { validPng } from "@/lib/shop/validation";
import { CARD_OFFER, isOfferCard } from "@/lib/shop/offers";
import { cartIssues } from "@/lib/shop/cart-state";
import { readCart, addToCart, saveLogo } from "@/lib/shop/cart";
import { PurchaseConfidenceGrid } from "./purchase-confidence";
import { ProductMedia } from "./product-media";
import { StandeeGallery } from "./standee-gallery";
import { NFCCreationProcess } from "./nfc-creation-process";
export function ProductConfigurator({product,products,email,enabled}:{product:Product;products:Product[];email:string|null;enabled:boolean}){
 const purchaseActions=useRef<HTMLDivElement>(null);
 const buyButton=useRef<HTMLButtonElement>(null);
 const [checkout,setCheckout]=useState<CartItem[]|null>(null);const [variantId,setVariant]=useState(product.variants[0].id);const [qty,setQty]=useState(1);const [file,setFile]=useState<File|null>(null);const [error,setError]=useState("");const [added,setAdded]=useState(false);const [busy,setBusy]=useState(false);
 const variant=product.variants.find(v=>v.id===variantId)!;
 async function chooseLogo(f:File|undefined){setError("");setFile(null);if(!f)return;if(f.size>10*1024*1024||!validPng(new Uint8Array(await f.slice(0,8).arrayBuffer()))){setError("Please choose a PNG image under 10 MB.");return;}setFile(f);}
 async function add(buy:boolean){setBusy(true);setError("");setAdded(false);try{const candidate={id:crypto.randomUUID(),productSlug:product.slug,variantId,quantity:qty};const issues=cartIssues(buy?[candidate]:[...readCart(),candidate],products);if(issues.length)throw new Error(issues[0]);const logoId=file?crypto.randomUUID():null;if(file&&logoId)await saveLogo(logoId,file);const item={id:crypto.randomUUID(),productSlug:product.slug,variantId,quantity:qty,logoId,logoName:file?.name};if(buy){sessionStorage.setItem("nfc-buy-now",JSON.stringify([item]));sessionStorage.setItem("nfc-checkout-mode","buy");setCheckout([item]);}else{addToCart(item);setAdded(true);}}catch(e){setError(e instanceof Error?e.message:"Could not save your bag. Please retry.");}finally{setBusy(false);}}
 return <div className="product-detail">{product.kind==="standee"?<StandeeGallery/>:<ProductMedia key={"media-"+variant.id} variant={variant} name={product.name} isKeychain={product.kind==="keychain"}/>}<div className="product-config"><p className="shop-eyebrow">{product.platform} / {product.qr===false?"NFC":"NFC + QR"}</p><h1>{product.name}</h1><p className="product-description">{product.description}</p><strong className="product-price">{priceLabel(variant.price_paise)}</strong>{variant.price_paise===null&&<p className="muted"><a href="mailto:hello@hiy.agency">Ask our team for a price</a></p>}
 {variant.price_paise!==null&&<p className="muted">List price · +18% GST. {product.shipping?"NimbusPost shipping calculated at checkout.":"Shipping quote awaits packed parcel measurements."}</p>}
 {product.stock!==undefined&&<p role="status">{product.stock>0?`${product.stock} in stock`:"Sold out"} · Stock shared across designs</p>}<a className="plain-button" href="#reviews-title">Read or write customer reviews</a>{product.qr!==false&&<p className="standee-qr-note">Every NFC.HIY product with a printed QR uses a custom smart QR setup powered by U2L.AI. Our team can update its destination later, so a changed link needn’t mean a replacement product.</p>}{!product.shipping&&<p className="muted">Courier quote pending packed parcel measurements. {product.kind==="standee"?"The 4 × 6 inch display size is not the shipping box size.":"Contact our team for a quote."}</p>}{product.packedWeightGrams&&!product.shipping&&<p>Packed weight: {product.packedWeightGrams} g. Parcel dimensions awaiting confirmation.</p>}{product.shipping&&<p className="muted">Packed shipping weight: {product.shipping.weightGrams} g per item · {product.shipping.weightGrams*qty} g for this quantity. Courier charges may also depend on parcel size.</p>}
 {isOfferCard(product.slug)&&<div className="cart-offer"><strong>{CARD_OFFER.title}</strong><p>{CARD_OFFER.description}</p></div>}
 {product.variants.length>1&&<fieldset className="variant-options"><legend>Choose your design</legend>{product.variants.map(v=><button type="button" key={v.id} aria-pressed={variantId===v.id} onClick={()=>{setVariant(v.id);setAdded(false);}}>{v.name}</button>)}</fieldset>}
 <div className="configuration-row"><label htmlFor="quantity">Quantity</label><input id="quantity" type="number" min={1} max={product.stock??50} value={qty} onChange={e=>setQty(Math.max(1,Math.min(50,Number(e.target.value)||1)))}/></div>
 {product.customLogo!==false&&<label className="logo-upload"><Upload size={20}/><span><strong>{file?file.name:"Make it yours. Add your logo."}</strong><small>Optional · PNG only · Up to 10 MB</small></span><input aria-label="Upload your PNG logo" type="file" accept="image/png,.png" onChange={e=>chooseLogo(e.target.files?.[0])}/></label>}{file&&<button className="plain-button" onClick={()=>setFile(null)}>Remove logo</button>}
 {product.kind==="standee"&&<aside className="standee-design-included"><strong>Professional custom design — on the house.</strong><p>Designing is completely free with your standee. Our professional designers create your artwork around your brand, colours and theme. You approve the design on WhatsApp before we produce it.</p></aside>}
 <p className="customisation-note">{product.kind==="keychain"?"Our team will contact you on WhatsApp to confirm your link and setup requirements before dispatch.":"Our team will message you on WhatsApp to collect your links and confirm the design before production."}</p>
 {error&&<p role="alert" className="shop-error">{error}</p>}
 <div className="purchase-actions" ref={purchaseActions}>{variant.price_paise===null?<a className="shop-button" href={`https://wa.me/919109167827?text=${encodeURIComponent(`Hi NFC.HIY, I’d like a price and shipping quote for ${qty} × ${product.name} (${variant.name}).`)}`} target="_blank" rel="noreferrer">Ask for a quote <ArrowRight size={18}/></a>:<><button className="shop-button" disabled={busy||variant.price_paise===null||!variant.available||!product.active||product.stock===0||qty>(product.stock??50)} onClick={()=>add(false)}>{added?<Check size={18}/>:<ShoppingBag size={18}/>} {added?"Added to cart":"Add to Cart"}</button><button ref={buyButton} className="shop-button secondary" disabled={busy||variant.price_paise===null||!variant.available||!product.active||product.stock===0||qty>(product.stock??50)} onClick={()=>add(true)}>Buy now <ArrowRight size={18}/></button></>}</div>
 {added&&<p role="status">Added. <a href="/cart">View your bag →</a></p>}{!variant.available&&<p>Currently unavailable.</p>}
 <PurchaseConfidenceGrid product={product} variantAvailable={variant.available}/>
 <p className="product-assurance"><ShieldCheck size={17}/> {product.kind==="keychain"?"Setup confirmation before dispatch":"Design approval before production"}</p>
 {[["Technical specifications",product.specifications],["Materials",product.materials],["How to use",product.instructions]].filter(([,v])=>v).map(([title,value])=><details key={title}><summary>{title}</summary><p>{value}</p></details>)}
 <CartExtras products={products} excluded={[product.slug]} onAdd={p=>{const v=p.variants.find(v=>v.available&&v.price_paise!==null);if(!v)return;try{const extra={id:crypto.randomUUID(),productSlug:p.slug,variantId:v.id,quantity:1};const issues=cartIssues([...readCart(),extra],products);if(issues.length)throw new Error(issues[0]);addToCart(extra);setAdded(true);}catch(e){setError((e as Error).message);}}}/>
 </div><StickyMobileCart target={purchaseActions} price={priceLabel(variant.price_paise)} disabled={busy||variant.price_paise===null||!variant.available||!product.active||product.stock===0||qty>(product.stock??50)} hidden={!!checkout||variant.price_paise===null} message={error|| (added?"Added to your cart":"")} onAdd={()=>void add(false)}/>{product.kind!=="keychain"&&product.kind!=="standee"&&<NFCCreationProcess key={variant.id} productImage={variant.image} productName={product.name}/ >}{checkout&&<CheckoutDialog items={checkout} products={products} email={email} enabled={enabled} onClose={()=>{setCheckout(null);requestAnimationFrame(()=>buyButton.current?.focus());}}/>}</div>;
}
