"use client";
import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import { Play, ZoomIn, X } from "lucide-react";
import type { Variant } from "@/lib/shop/catalogue";
export function ProductMedia({variant,name,isKeychain=false}:{variant:Variant;name:string;isKeychain?:boolean}){
 const [playing,setPlaying]=useState(false),[failed,setFailed]=useState(false);const ref=useRef<HTMLVideoElement>(null);const zoom=useRef<HTMLDialogElement>(null);const touch=useRef<number|null>(null);
 useEffect(()=>{const dialog=zoom.current;if(!dialog)return;let previous:string|null=null;const restore=()=>{if(previous!==null){document.body.style.overflow=previous;previous=null;}};const observer=new MutationObserver(()=>{if(dialog.open&&previous===null){previous=document.body.style.overflow;document.body.style.overflow="hidden";}else if(!dialog.open)restore();});observer.observe(dialog,{attributes:true,attributeFilter:["open"]});return()=>{observer.disconnect();restore();};},[]);
 useEffect(()=>{const node=ref.current;if(!node)return;const observer=new IntersectionObserver(([e])=>{if(!e.isIntersecting)node.pause();});observer.observe(node);return()=>observer.disconnect();},[playing]);
 const video=!!variant.video&&!failed;
 return <div className="product-media"><div className="product-media-stage" onTouchStart={e=>{touch.current=e.touches[0].clientX;}} onTouchEnd={e=>{if(touch.current!==null&&video&&Math.abs(e.changedTouches[0].clientX-touch.current)>65)setPlaying(e.changedTouches[0].clientX<touch.current);touch.current=null;}}>
 {playing&&video?<video ref={ref} src={variant.video} controls muted playsInline preload="metadata" onError={()=>{setPlaying(false);setFailed(true);}} aria-label={name+" product animation"}/>:<button className="gallery-zoom-trigger" onClick={()=>zoom.current?.showModal()} aria-label={"Enlarge "+name+" product image"}><Image src={variant.image} alt={isKeychain?name:name+" front and back"} width={500} height={500} priority sizes="(max-width: 800px) 90vw, 48vw"/><span><ZoomIn size={17}/> View image</span></button>}</div>
 <div className="gallery-thumbnails" role="group" aria-label="Product media"><button aria-pressed={!playing} onClick={()=>setPlaying(false)}><Image src={variant.image} alt="" width={48} height={48}/><span>Photo</span></button>{video&&<button aria-pressed={playing} onClick={()=>setPlaying(true)}><Play size={19}/><span>Product film</span></button>}</div>{failed&&<p role="status">The video is unavailable. The product photo is shown instead.</p>}<p>{isKeychain?"AI-enhanced product visual · Set contents listed in specifications":"Product visualisation · Final design confirmed with you"}</p>
 <dialog ref={zoom} className="gallery-dialog" aria-label={name+" enlarged photo"} onClick={e=>{if(e.target===zoom.current)zoom.current.close();}}><button autoFocus onClick={()=>zoom.current?.close()} aria-label="Close enlarged photo"><X/></button><Image src={variant.image} width={500} height={500} sizes="(max-width: 560px) 85vw, 500px" alt={name+" enlarged product view"}/></dialog></div>;
}
