"use client";
/* eslint-disable @next/next/no-img-element -- private signed photos are already resized on upload */
import { useState } from "react";
import type { PublicReview } from "@/lib/shop/reviews";
import { GoogleButton } from "./google-button";
export function Reviews({slug,email,reviews,available}:{slug:string;email:string|null;reviews:PublicReview[];available:boolean}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(""),[done,setDone]=useState(false);
 return <section className="product-reviews" aria-labelledby="reviews-title" data-clarity-mask="true"><p className="shop-eyebrow">FROM THE COMMUNITY</p><h2 id="reviews-title">Customer reviews</h2>
 {!reviews.length&&<p>No published reviews yet. Share your experience with this product.</p>}
 <div className="review-grid">{reviews.map(r=><article key={r.id}><strong>{r.display_name}</strong><p aria-label={r.rating+" out of 5 stars"}>{"★".repeat(r.rating)}{"☆".repeat(5-r.rating)}</p>{r.verified_purchase&&<small>Verified purchase</small>}<p className="review-body">{r.body}</p><div className="review-photos">{r.photos.map(url=><a key={url} href={url} target="_blank" rel="noreferrer">{/* Signed private-storage URL. */}{ }<img src={url} alt={"Customer photo for "+slug.replaceAll("-"," ")} width={160} height={160} loading="lazy"/></a>)}</div><time dateTime={r.created_at}>{new Date(r.created_at).toLocaleDateString("en-IN",{timeZone:"Asia/Kolkata"})}</time></article>)}</div>
 {!available?<p>Review submissions will open soon.</p>:!email?<div><p>Sign in to write a review and add your photos.</p><GoogleButton next={"/products/"+slug}/></div>:done?<p role="status">{message}</p>:<form className="review-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;setBusy(true);setMessage("");try{const data=new FormData(form);data.set("slug",slug);const res=await fetch("/api/shop/reviews",{method:"POST",body:data});const result=await res.json();if(!res.ok)throw new Error(result.error||"Could not submit review.");setDone(true);setMessage(result.message);form.reset();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>
 <h3>Share your experience</h3><label>Display name<input name="name" required minLength={2} maxLength={60}/></label><label>Your rating<select name="rating" required defaultValue=""><option value="" disabled>Choose a rating</option>{[5,4,3,2,1].map(n=><option value={n} key={n}>{n} star{n!==1?"s":""}</option>)}</select></label><label>Your review<textarea name="body" required minLength={10} maxLength={2000} rows={4}/></label><label>Photos (optional, up to 2, 1 MB each)<input name="photos" type="file" multiple accept="image/jpeg,image/png,image/webp"/></label><label className="consent"><input type="checkbox" name="consent" required/><span>I agree to publish my display name, review and photos. They contain no private information and reflect my own experience.</span></label><button className="shop-button" disabled={busy}>{busy?"Submitting…":"Submit review"}</button>{message&&<p role="alert">{message}</p>}<small>All ratings are welcome. Reviews are checked for spam, private information and relevance before publication.</small></form>}
 </section>;
}
