import { requireOwner } from "@/lib/admin-auth";
import { commerceDb } from "@/lib/shop/server";
import { revalidatePath } from "next/cache";
import { priceLabel } from "@/lib/shop/catalogue";
const currentTime = () => Date.now();
async function update(form:FormData){"use server";await requireOwner();const status=String(form.get("status"));if(!["open","contacted","closed"].includes(status))throw new Error("Invalid status");const {error}=await commerceDb().from("shop_abandoned_carts").update({status}).eq("user_id",String(form.get("id")));if(error)throw new Error("Could not update cart");revalidatePath("/admin/abandoned-carts");}
export default async function AbandonedCarts(){
 await requireOwner();const db=commerceDb();
 const now=currentTime();
 const {error:cleanupError}=await db.from("shop_abandoned_carts").delete().lt("updated_at",new Date(now-30*86400000).toISOString());
 const {data,error}=await db.from("shop_abandoned_carts").select("*").order("updated_at",{ascending:false}).limit(200);
 return <main className="admin-main" data-clarity-mask="true"><h1>Abandoned carts</h1><p>Customers who explicitly saved their checkout for follow-up. A cart is abandoned after 30 minutes without an update. Anonymous browsing cannot reveal phone numbers. Paid carts are removed automatically. Latest 200 records; records expire after 30 days.</p>{error||cleanupError?<p role="alert">Cart tracking is unavailable. Apply the abandoned carts database migration and retry.</p>:!data?.length?<section className="admin-panel">No saved carts yet.</section>:data.map(cart=><article className="admin-panel" key={cart.user_id}><h2>{cart.name}</h2><p>{now-Date.parse(cart.updated_at)>=1800000?"Abandoned":"Recently saved"} · {cart.status} · Last saved {new Date(cart.updated_at).toLocaleString("en-IN",{timeZone:"Asia/Kolkata"})} IST</p><p><a href={`tel:+91${cart.phone}`}>{cart.phone}</a> · {cart.email}</p><ul>{(cart.items as {product:string;variant:string;quantity:number;price_paise:number|null;logo_attached:boolean}[]).map((i,n)=><li key={n}>{i.product} — {i.variant} × {i.quantity} · {priceLabel(i.price_paise===null?null:i.price_paise*i.quantity)}{i.logo_attached?" · Logo selected":""}</li>)}</ul><p>Item amounts before offers, tax and shipping. This is not an order or reserved stock.</p><a href={`https://wa.me/91${cart.phone}?text=${encodeURIComponent(`Hi ${cart.name}, you saved a cart with NFC.HIY and asked for checkout help. Would you like help completing your purchase?`)}`} target="_blank" rel="noreferrer">Contact on WhatsApp</a><form action={update}><input type="hidden" name="id" value={cart.user_id}/><button name="status" value="contacted">Mark contacted</button>{" "}<button name="status" value="closed">Close</button>{" "}<button name="status" value="open">Reopen</button></form></article>)}</main>;
}
