"use client";
import { useState } from "react";
import type { Product } from "@/lib/shop/catalogue";
import { saveProduct } from "@/app/admin/commerce-actions";
export function CatalogueEditor({product,connected}:{product:Product;connected:boolean}){const [p,setP]=useState(product),[busy,setBusy]=useState(false),[message,setMessage]=useState("");function field(key:keyof Product,value:unknown){setP({...p,[key]:value});}
 return <details className="admin-panel"><summary style={{cursor:"pointer",padding:16}}>{p.name} · {p.variants.length} design{p.variants.length>1?"s":""}</summary><form className="commerce-admin-form" onSubmit={async e=>{e.preventDefault();setBusy(true);const r=await saveProduct(p);setMessage(r.error||"Saved. Your product page is updated.");setBusy(false);}}><label>Product name<input value={p.name} onChange={e=>field("name",e.target.value)} required/></label><label>Description<textarea value={p.description} onChange={e=>field("description",e.target.value)} required/></label><label>Visible in shop<input type="checkbox" checked={p.active} onChange={e=>field("active",e.target.checked)}/></label>
 {p.variants.map((v,i)=><fieldset key={v.id}><legend>{v.name}</legend><label>Price in rupees (blank shows xxx)<input type="number" min=".01" step=".01" value={v.price_paise===null?"":v.price_paise/100} onChange={e=>field("variants",p.variants.map((row,j)=>j===i?{...row,price_paise:e.target.value===""?null:Math.round(Number(e.target.value)*100)}:row))}/></label><label>Available<input type="checkbox" checked={v.available} onChange={e=>field("variants",p.variants.map((row,j)=>j===i?{...row,available:e.target.checked}:row))}/></label>{(["image","video"] as const).map(k=><label key={k}>{k==="image"?"Image path":"Video path (blank hides video)"}<input value={v[k]} onChange={e=>field("variants",p.variants.map((row,j)=>j===i?{...row,[k]:e.target.value}:row))}/></label>)}</fieldset>)}
 {(["specifications","materials","instructions"] as const).map(k=><label key={k}>{k} (blank stays hidden)<textarea value={p[k]} onChange={e=>field(k,e.target.value)}/></label>)}<button disabled={busy||!connected}>{busy?"Saving…":"Save product"}</button>{message&&<p role="status">{message}</p>}</form></details>;
}

