"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { orderOperation,recordOrderExpense } from "@/app/admin/commerce-actions";
export function OrderControls({id,stage,phone,reference,hasShipment,managedStatuses=false}:{id:string;stage:string;phone:string;reference:string;hasShipment:boolean;managedStatuses?:boolean}){
 const [busy,setBusy]=useState(false),[result,setResult]=useState(""),[message,setMessage]=useState("Hi! Thank you for your order "+reference+" from NFC.HIY. Please share your destination links so we can prepare your design for approval.");const router=useRouter();
 const next:Record<string,string>=managedStatuses?{}:{awaiting_design:"design_approved",design_approved:"production",production:"ready_to_ship"};
 async function run(operation:string,value?:string){setBusy(true);const r=await orderOperation(id,operation,value);setResult(r.error||"Updated.");setBusy(false);router.refresh();}
 return <section className="admin-panel"><h2>Design & fulfilment</h2><div className="commerce-admin-form"><label>WhatsApp message<textarea value={message} onChange={e=>setMessage(e.target.value)}/></label><a className="commerce-admin-button" href={"https://wa.me/91"+phone.replace(/\D/g,"").slice(-10)+"?text="+encodeURIComponent(message)} target="_blank" rel="noreferrer">Open WhatsApp to contact buyer ↗</a>{next[stage]&&<button disabled={busy} onClick={()=>run("stage",next[stage])}>Mark {next[stage].replaceAll("_"," ")}</button>}{stage==="ready_to_ship"&&!hasShipment&&<button disabled={busy} onClick={()=>run("book")}>Book shipment</button>}{hasShipment&&<><button disabled={busy} onClick={()=>run("track")}>Refresh tracking</button><button disabled={busy} onClick={()=>run("label")}>Get shipping label</button></>}</div><h3>Record an actual expense</h3><p>Record refunds already processed in the payment gateway or shipping fees already charged. This does not issue a refund.</p><form className="commerce-admin-form" onSubmit={async e=>{e.preventDefault();setBusy(true);const d=new FormData(e.currentTarget);const r=await recordOrderExpense(id,{amount:Math.round(Number(d.get("amount"))*100),reference:String(d.get("reference")),category:String(d.get("category"))});setResult(r.error||"Expense recorded.");setBusy(false);router.refresh();}}><label>Category<select name="category"><option value="order_shipping">Shipping expense</option><option value="order_refund">Completed refund</option></select></label><label>Amount (₹)<input name="amount" type="number" min=".01" step=".01" required/></label><label>Unique provider transaction reference<input name="reference" minLength={3} maxLength={100} required/></label><button disabled={busy}>Record expense</button></form>{result&&<p role="status">{result}</p>}</section>;
}
