import "server-only";
import type { Address } from "./validation";
export type Parcel={length:number;width:number;height:number;weight:number};
export function parcelFor(quantity:number):Parcel{const p={length:Number(process.env.PARCEL_LENGTH_CM),width:Number(process.env.PARCEL_WIDTH_CM),height:Number(process.env.PARCEL_UNIT_HEIGHT_CM)*quantity,weight:Number(process.env.PARCEL_UNIT_WEIGHT_KG)*quantity};if(Object.values(p).some(v=>!Number.isFinite(v)||v<=0)||p.weight>10)throw new Error("This quantity requires a custom shipping quote. Please contact our team.");return p;}
export async function ithink(path:string,data:Record<string,unknown>){if(!process.env.ITHINK_ACCESS_TOKEN||!process.env.ITHINK_SECRET_KEY)throw new Error("Shipping is not configured.");const host=process.env.ITHINK_ENV==="production"?"https://my.ithinklogistics.com":"https://pre-alpha.ithinklogistics.com";const res=await fetch(host+"/api_v3/"+path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({data:{...data,access_token:process.env.ITHINK_ACCESS_TOKEN,secret_key:process.env.ITHINK_SECRET_KEY}}),cache:"no-store",signal:AbortSignal.timeout(20000)});if(!res.ok)throw new Error("Shipping provider is temporarily unavailable.");const result=await res.json();if(Number(result.status_code)!==200)throw new Error("Shipping provider could not complete this request.");return result;}
export async function quoteShipping(pincode:string,quantity:number,subtotal:number){const parcel=parcelFor(quantity);const result=await ithink("rate/check.json",{from_pincode:process.env.ITHINK_PICKUP_PINCODE,to_pincode:pincode,shipping_length_cms:parcel.length,shipping_width_cms:parcel.width,shipping_height_cms:parcel.height,shipping_weight_kg:parcel.weight,order_type:"forward",payment_method:"Prepaid",product_mrp:(subtotal/100).toFixed(2)});const courier=process.env.ITHINK_COURIER?.toLowerCase();const rates=Object.values(result.data||{}) as {logistic_name:string;rate:number;prepaid:string;pickup:string;logistic_service_type?:string}[];const match=rates.find(r=>r.logistic_name?.toLowerCase()===courier&&r.prepaid==="Y"&&r.pickup==="Y"&&(!process.env.ITHINK_SERVICE||r.logistic_service_type===process.env.ITHINK_SERVICE));if(!match||!Number.isFinite(Number(match.rate))||Number(match.rate)<0)throw new Error("Shipping is not available for this PIN code. Contact our team.");return {amount:Math.round(Number(match.rate)*100),courier:match.logistic_name,parcel};}
export async function bookShipment(order:{reference:string;created_at:string;total_paise:number;shipping_paise:number;email:string;address:Address;courier:string;parcel:Parcel},items:{name:string;variant_id:string;quantity:number;price_paise:number}[]){const a=order.address;const result=await ithink("order/add.json",{pickup_address_id:process.env.ITHINK_PICKUP_ID,return_address_id:process.env.ITHINK_RETURN_ID,logistics:order.courier.toLowerCase(),s_type:process.env.ITHINK_SERVICE||"surface",order_type:"forward",shipments:[{order:order.reference,order_date:order.created_at.slice(0,10).split("-").reverse().join("-"),total_amount:order.total_paise/100,name:a.name,add:a.line1,add2:a.line2,pin:a.pincode,city:a.city,state:a.state,country:"India",phone:a.phone,email:order.email,is_billing_same_as_shipping:"yes",billing_name:a.name,billing_add:a.line1,billing_pin:a.pincode,billing_phone:a.phone,products:items.map(i=>({product_name:i.name,product_sku:i.variant_id,product_quantity:i.quantity,product_price:i.price_paise/100})),shipment_length:order.parcel.length,shipment_width:order.parcel.width,shipment_height:order.parcel.height,weight:order.parcel.weight,shipping_charges:order.shipping_paise/100,payment_mode:"Prepaid",cod_amount:0}]});const first=Object.values(result.data||{})[0] as {waybill?:string;awb_no?:string;status?:string}|undefined;const awb=first?.waybill||first?.awb_no;if(!awb)throw new Error("Booking response requires review in iThink before retrying.");return String(awb);}
export async function tracking(awb:string){const r=await ithink("order/track.json",{awb_number_list:awb});const d=r.data?.[awb];if(!d)throw new Error("Tracking has not updated yet.");return {status:String(d.current_status||"Awaiting carrier update"),expected:String(d.expected_delivery_date||""),scans:d.scan_details||[],updated:new Date().toISOString()};}
export async function shipmentLabel(awb:string){const result=await ithink("shipping/label.json",{awb_numbers:awb,page_size:"A4"});const url=new URL(result.file_name);if(!url.hostname.endsWith(".ithinklogistics.com"))throw new Error("Invalid label response.");url.protocol="https:";return url.href;}

