"use server";
import { z } from "zod";
import { revalidatePath } from "next/cache";
import { requireOwner } from "@/lib/admin-auth";
import { commerceDb } from "@/lib/shop/server";
import { bookShipment,shipmentLabel,tracking } from "@/lib/shop/ithink";
const media=z.string().regex(/^\/shop\/[a-z0-9-]+\.(webp|png|jpg|mp4)$/);
const productSchema=z.object({slug:z.string().regex(/^[a-z0-9-]+$/),name:z.string().trim().min(2).max(100),platform:z.string().min(1).max(40),description:z.string().trim().min(1).max(1500),colour:z.string().regex(/^#[a-f0-9]{6}$/i),category:z.enum(["Social","Reviews","All-in-one"]),active:z.boolean(),specifications:z.string().max(5000),materials:z.string().max(5000),instructions:z.string().max(5000),variants:z.array(z.object({id:z.string().regex(/^[a-z0-9-]+$/),name:z.string().min(1).max(80),image:media,video:z.union([media,z.literal("")]),price_paise:z.number().int().positive().max(100000000).nullable(),available:z.boolean()})).min(1).max(20)});
export async function saveProduct(input:unknown){await requireOwner();try{const data=productSchema.parse(input);const {error}=await commerceDb().from("shop_products").update({data,updated_at:new Date().toISOString()}).eq("slug",data.slug).select().single();if(error)throw new Error("Catalogue is not configured yet. Apply the commerce migration and seed first.");revalidatePath("/");revalidatePath("/products/"+data.slug);revalidatePath("/admin/catalogue");return {ok:true};}catch(e){return {error:(e as Error).message};}}
export async function orderOperation(id:string,operation:string,value?:string){await requireOwner();try{z.string().uuid().parse(id);const db=commerceDb();if(operation==="stage"){const {error}=await db.rpc("shop_advance_order",{p_id:id,p_stage:value});if(error)throw new Error("This status change is not allowed. Refresh the order.");}
 else if(operation==="book"){const {data:o}=await db.from("shop_orders").select("*,shop_order_items(*)").eq("id",id).single();if(!o||o.stage!=="ready_to_ship"||o.payment_status!=="paid")throw new Error("Only paid, ready-to-ship orders can be booked.");const {error:lock}=await db.from("shop_fulfilments").insert({order_id:id,booking_status:"booking"});if(lock)throw new Error("A booking exists or is awaiting review. Check iThink before taking further action.");try{const awb=await bookShipment(o,o.shop_order_items);const {error:saveError}=await db.from("shop_fulfilments").update({awb,booking_status:"booked"}).eq("order_id",id);if(saveError)throw new Error("Booking succeeded but could not be saved. Reconcile in iThink.");await db.from("shop_orders").update({stage:"shipped"}).eq("id",id);await db.from("shop_order_events").insert({order_id:id,label:"Shipped. Tracking number: "+awb});}catch(e){await db.from("shop_fulfilments").update({booking_status:"review",error:"Check this order in iThink before any retry."}).eq("order_id",id);throw e;}}
 else if(operation==="label"||operation==="track"){const {data:f}=await db.from("shop_fulfilments").select("awb").eq("order_id",id).single();if(!f?.awb)throw new Error("No tracking number available.");if(operation==="label"){const url=await shipmentLabel(f.awb);await db.from("shop_fulfilments").update({label_url:url}).eq("order_id",id);}else{const result=await tracking(f.awb);await db.from("shop_fulfilments").update({tracking:result,checked_at:new Date().toISOString()}).eq("order_id",id);if(result.status==="Delivered")await db.from("shop_orders").update({stage:"delivered"}).eq("id",id).eq("stage","shipped");}}
 else throw new Error("Unknown action.");
 revalidatePath("/admin/orders");revalidatePath("/admin/orders/"+id);revalidatePath("/account/orders/"+id);return {ok:true};}catch(e){return {error:(e as Error).message};}}
export async function recordOrderExpense(id:string,input:{amount:number;reference:string;category:string}){await requireOwner();try{z.string().uuid().parse(id);const v=z.object({amount:z.number().int().positive().max(100000000),reference:z.string().trim().min(3).max(100),category:z.enum(["order_refund","order_shipping"])}).parse(input);const {error}=await commerceDb().rpc("shop_record_expense",{p_id:id,p_amount:v.amount,p_reference:v.category+":"+v.reference,p_category:v.category});if(error)throw new Error("Could not record expense. Verify the amount and reference.");revalidatePath("/admin");revalidatePath("/admin/finances");revalidatePath("/admin/orders/"+id);return {ok:true};}catch(e){return {error:(e as Error).message};}}

